export const categories = [
  "Interview Questions",
  "Practical Scenarios",
  "Debugging",
  "Projects",
  "Authentication",
  "Performance",
  "Frontend",
  "Backend",
  "DevOps"
];

export const technologies = [
  "HTML",
  "CSS",
  "JS",
  "React",
  "Node.js",
  "TypeScript",
  "Python",
  "MongoDB",
  "System Design",
  "AWS",
  "Docker"
];

export const mockProblems = [
  {
    id: "p1",
    title: "React useEffect Infinite Loop",
    difficulty: "Easy",
    technology: "React",
    category: "Debugging",
    description: "Users report repeated API requests crashing the server. Fix the dependency array in the main dashboard component.",
    xp: 50,
    timeEst: "10m",
    successRate: "82%",
    status: "Review",
    color: "green",
    locked: false,
  },
  {
    id: "p2",
    title: "Distributed Lock Implementation",
    difficulty: "Hard",
    technology: "Node.js",
    category: "Backend",
    description: "Design a Redis-based distributed lock to prevent race conditions in the microservices payment gateway.",
    xp: 250,
    timeEst: "45m",
    successRate: "12%",
    status: "Solve",
    color: "red",
    locked: false,
  },
  {
    id: "p3",
    title: "Virtual DOM Diffing",
    difficulty: "Medium",
    technology: "React",
    category: "Frontend",
    description: "Implement a simplified VDOM algorithm to efficiently update the actual DOM structure without full re-renders.",
    xp: 100,
    timeEst: "30m",
    successRate: "45%",
    status: "Continue",
    color: "amber",
    locked: false,
  },
  {
    id: "p4",
    title: "Mastering K8s Ingress",
    difficulty: "Expert",
    technology: "Docker",
    category: "DevOps",
    description: "Configure advanced routing rules and TLS termination for a multi-tenant microservices cluster.",
    xp: 500,
    timeEst: "2h",
    successRate: "5%",
    status: "Locked",
    color: "fuchsia",
    locked: true,
    unlockLevel: 20
  },
  {
    id: "p5",
    title: "Type-safe API Wrapper",
    difficulty: "Medium",
    technology: "TypeScript",
    category: "Practical Scenarios",
    description: "Create a strongly-typed generic fetch wrapper that infers return types based on the endpoint path.",
    xp: 120,
    timeEst: "25m",
    successRate: "55%",
    status: "Solve",
    color: "amber",
    locked: false,
  },
  {
    id: "p6",
    title: "Rate Limiter with Sliding Window",
    difficulty: "Hard",
    technology: "System Design",
    category: "Interview Questions",
    description: "Design and implement a sliding window rate limiter that scales across multiple distributed nodes.",
    xp: 300,
    timeEst: "1h",
    successRate: "18%",
    status: "Solve",
    color: "red",
    locked: false,
  }
];
